data = [
    {"title":"Nightcrawling",
    "author":"Leila Mottley",
    "gender":"Female",
    "religion":"Christianity",
    "race":"Black",
    "sexuality":"Straight",
    "description":"Based on a true crime in 2015 involving institutional exploitation, brutality and corruption in the Oakland police department, Nightcrawling gives voice to 17-year-old Kiara Johnson, who, after her father's death and mother's detention in a rehab facility, becomes a sex worker to pay for rent hikes."},
    {"title":"The Street",
     "author":"Ann Petry",
     "gender":"Female",
     "religion":"Christianity",
     "race":"Black",
     "sexuality":"NaN",
     "description":"Ann Petry’s ‘The Street’ is a commentary on the social injustices that confronted her character, Lutie Johnson, as a single black mother during this period. Lutie is confronted by racism, sexism, and classism on a daily basis in her pursuit of the American dream for herself and her son, Bub."},
    {"title":"A Suitable Boy",
     "author":"Vikram Seth",
     "gender":"Male",
     "religion":"Hindu",
     "race":"South_Asian",
     "sexuality":"NaN",
     "description":"Set in Brahmpur, India (a fictional town), A Suitable Boy concerns the fortunes and trials of four elite families over the course of 18 months: the Mehras, the Kapoors, the Chatterjis and the Khans (the last being the only Muslim family of the group). It especially focuses on the plight of 19-year-old Lata Mehra, a talented student at the local Brahmpur University."},
     {"title":"No Honour",
      "author":"Awais Khan",
      "gender":"Female",
      "religion":"Islam",
      "race":"South_Asian",
      "sexuality":"NaN","description":"A young woman defies convention in a small Pakistani village, with devastating results for her and her family. A stunning, immense beautiful novel about courage, family and the meaning of love, when everything seems lost."},
      {"title":"A Tale for the Time Being",
       "author":"Ruth Ozeki",
       "gender":"Female",
       "religion":"Buddhism",
       "race":"South_Asian",
       "sexuality":"NaN",
       "description":"In Tokyo, sixteen-year-old Nao has decided there's only one escape from her aching loneliness and her classmates' bullying. But before she ends it all, Nao first plans to document the life of her great grandmother, a Buddhist nun who's lived more than a century."},
       {"title":"Fiebre Tropical",
        "author":"Julián Delgado Lopera",
        "gender":"Male",
        "religion":"Christianity",
        "race":"Latinx",
        "sexuality":"Gay/Lesbian",
        "description":"Uprooted from Bogotá into an ant-infested Miami townhouse, fifteen-year-old Francisca is miserable in her strange new city. Her alienation grows when her mother is swept up in an evangelical church, replete with abstinent salsa dancers and baptisms for the dead. But there, Francisca meets the magnetic Carmen: head of the youth group and the pastor’s daughter."},
       {"title":"The Sound of Stars",
        "author":"Alechia Dow",
        "gender":"Non-binary",
        "religion":"Atheist",
        "race":"Black",
        "sexuality":"Bisexual",
        "description":"Ellie’s—and humanity’s—fate rests in the hands of an alien she should fear. M0Rr1S has a lot of secrets, but also a potential solution—thousands of miles away. The two embark on a wild and dangerous road trip with a bag of books and their favourite albums, all the while creating a story and a song of their own that just might save them both."},
       {"title":"Sour Heart",
        "author":"Jenny Zhang",
        "gender":"Female",
        "religion":"Agnostic",
        "race":"East_Asian",
        "sexuality":"NaN",
        "description":"Narrated by the daughters of Chinese immigrants who fled imperilled lives as artists back home only to struggle to stay afloat — dumpster diving for food and scamming Atlantic City casino buses to make a buck — these seven stories showcase Zhang's compassion and moral courage, and a darkly funny and intimate rendering of girlhood."},
       {"title":"Doubting Thomas",
        "author":"Matthew Clark Davison",
        "gender":"Male",
        "religion":"Christianity",
        "race":"White",
        "sexuality":"Queer",
        "description":"Thomas McGurrin is a fourth-grade teacher and openly gay man at a private primary school serving Portland, Oregon's wealthy progressive elite when he is falsely accused of inappropriately touching a male student. Davison's novel explores the discrepancy between the progressive ideals and persistent negative stereotypes among the privileged regarding social status, race, and sexual orientation and the impact of that discrepancy on friendships and family relations."},
       {"title":"Dear Herculine",
        "author":"Aaron Apps",
        "gender":"Male",
        "religion":"Judaism",
        "race":"White",
        "sexuality":"Intersex",
        "description":"Dear Herculine is an intertextual project that recalls portions of the 19th-century French hermaphrodite Herculine Barbin's memoirs, discovered and re- published by Michel Foucault. The medical reassignment of Herculine's gender eventually led to his/her death in February of 1868. Herculine's experiences are set against and interwoven into the author's experiences as an intersexed body through the epistolary form."},
       {"title":"Not Your Backup",
        "author":"C.B. Lee",
        "gender":"Non-binary",
        "religion":"Atheist",
        "race":"East_Asian",
        "sexuality":"Asexual",
        "description":"Emma Robledo has a few more responsibilities than the usual high school senior, but then again, she and her friends have left school to lead a fractured Resistance movement against a corrupt Heroes League of Heroes. Emma is the only member of a supercharged team without powers, but as the Resistance moves to challenge the League, Emma realizes where her place is in this fight: at the front."},
       {"title":"Milk and Honey",
        "author":"Rupi Kaur",
        "gender":"Female",
        "religion":"Sikhism",
        "race":"South_Asian",
        "sexuality":"Queer",
        "description":"Milk and Honey is grounded in the everyday experiences of women and bears witness to both the beautiful and the brutal sides of being a woman. The collection is divided into four chapters—the hurting, the loving, the breaking, and the healing—each dealing with a different kind of experience and pain."}
       ]